local _, L = ...;
if GetLocale() == "ruRU" then
	L.L["%s (%s) by %s"] = "%s (%s) от %s"
	L.L["A new version of Steps is available."] = "Доступна новая версия Steps."
	L.L["chat"] = "чат"
	L.L["Cycle through display options."] = "Переключение режимов отображения."
	L.L["display"] = "отображение"
	L.L["guild"] = "гильдия"
	L.L["help"] = "помощь"
	L.L["instance"] = "подземелье"
	L.L["lock"] = "заблокировать"
	L.L["My steps today"] = "Мои шаги сегодня"
	L.L["party"] = "группа"
	L.L["Please /reload to disable chat integration."] = "Введите /reload, чтобы отключить интеграцию с чатом."
	L.L["Print this help."] = "Показать справку."
	L.L["raid"] = "рейд"
	L.L["Reset the position of the UI"] = "Сбросить положение интерфейса"
	L.L["reset"] = "сброс"
	L.L["Send steps to any chat"] = "Отправить шаги в любой чат"
	L.L["show"] = "показать"
	L.L["Steps"] = "Шаги"
	L.L["Toggle chat {steps} integration."] = "Включить/выключить интеграцию чата с {шаги}."
	L.L["Toggle display lock."] = "Заблокировать/разблокировать отображение."
	L.L["Toggle display."] = "Включить/выключить отображение."
	L.L["trend"] = "тренд"
	L.L["UI unlocked"] = "Интерфейс разблокирован"
	L.L["UI locked"] = "Интерфейс заблокирован"
	L.L["whisper"] = "шепот"
	L.L["yell"] = "крик"
	L.L["{steps} now enabled."] = "{шаги} включен."
	L.L["{steps}"] = "{шаги}"
	L.L["options"] = "настройки"
	L.L["Open the options panel"] = "Открыть панель настроек"
	L.L["dow"] = { [0]="Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб" }
	L.L["mon"] = { "янв", "фев", "мар", "апр", "май", "июн", "июл", "авг", "сен", "окт", "ноя", "дек" }
end