local _, L = ...;
if GetLocale() == "ptBR" then
	L.L["%s (%s) by %s"] = "%s (%s) por %s"
	L.L["A new version of Steps is available."] = "Uma nova versão do Steps está disponível."
	L.L["chat"] = "chat"
	L.L["Cycle through display options."] = "Alternar entre opções de exibição."
	L.L["display"] = "exibição"
	L.L["guild"] = "guilda"
	L.L["help"] = "ajuda"
	L.L["instance"] = "instância"
	L.L["lock"] = "travar"
	L.L["My steps today"] = "Meus passos de hoje"
	L.L["party"] = "grupo"
	L.L["Please /reload to disable chat integration."] = "Digite /reload para desativar a integração com o chat."
	L.L["Print this help."] = "Mostrar esta ajuda."
	L.L["raid"] = "raide"
	L.L["Reset the position of the UI"] = "Redefinir a posição da interface"
	L.L["reset"] = "redefinir"
	L.L["Send steps to any chat"] = "Enviar passos para qualquer chat"
	L.L["show"] = "mostrar"
	L.L["Steps"] = "Passos"
	L.L["Toggle chat {steps} integration."] = "Ativar ou desativar a integração do {passos} no chat."
	L.L["Toggle display lock."] = "Bloquear ou desbloquear a exibição."
	L.L["Toggle display."] = "Alternar exibição."
	L.L["trend"] = "tendência"
	L.L["UI unlocked"] = "Interface desbloqueada"
	L.L["UI locked"] = "Interface bloqueada"
	L.L["whisper"] = "sussurro"
	L.L["yell"] = "gritar"
	L.L["{steps} now enabled."] = "{passos} agora ativado."
	L.L["{steps}"] = "{passos}"
	L.L["options"] = "opções"
	L.L["Open the options panel"] = "Abrir o painel de opções"
	L.L["dow"] = { [0]="Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb" }
	L.L["mon"] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" }
end